#!/usr/bin/env python3
"""Generate a source map for flyto-docs scripts and VitePress functions."""

from __future__ import annotations

import argparse
import ast
import re
import sys
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "reference" / "docs-code.md"
SOURCE_PATTERNS = ("scripts/*.py", "scripts/*.mjs", ".vitepress/*.ts", ".vitepress/*.mts")
JS_FUNCTION_RE = re.compile(
    r"^(?:export\s+)?(?:async\s+)?function\s+([A-Za-z_$][\w$]*)\s*(\([^)]*\))",
    re.MULTILINE,
)
JS_METHOD_RE = re.compile(
    r"^\s{2,}([A-Za-z_$][\w$]*)\s*(\([^)]*\))\s*\{",
    re.MULTILINE,
)
JS_CONTROL_WORDS = {"catch", "for", "if", "switch", "while"}


def sources() -> list[Path]:
    return sorted({path for pattern in SOURCE_PATTERNS for path in ROOT.glob(pattern)})


def source_link(path: Path, line: int) -> str:
    relative = path.relative_to(ROOT).as_posix()
    return f"https://github.com/flytohub/flyto-docs/blob/main/{relative}#L{line}"


def python_declarations(path: Path) -> list[tuple[str, str, str, int]]:
    tree = ast.parse(path.read_text(encoding="utf-8"))
    declarations = []
    for node in ast.walk(tree):
        if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef, ast.ClassDef)):
            continue
        kind = "class" if isinstance(node, ast.ClassDef) else "function"
        if isinstance(node, ast.AsyncFunctionDef):
            prefix = "async def"
        elif isinstance(node, ast.FunctionDef):
            prefix = "def"
        else:
            prefix = "class"
        if isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
            signature = f"{prefix} {node.name}({ast.unparse(node.args)})"
        else:
            signature = f"{prefix} {node.name}"
        doc = ast.get_docstring(node) or f"Implements `{node.name}`."
        declarations.append((kind, signature, doc.splitlines()[0], node.lineno))
    return sorted(declarations, key=lambda item: item[3])


def javascript_declarations(path: Path) -> list[tuple[str, str, str, int]]:
    content = path.read_text(encoding="utf-8")
    declarations = []
    occupied = set()
    for regex, kind in ((JS_FUNCTION_RE, "function"), (JS_METHOD_RE, "method")):
        for match in regex.finditer(content):
            if kind == "method" and match.group(1) in JS_CONTROL_WORDS:
                continue
            line = content.count("\n", 0, match.start()) + 1
            key = (match.group(1), line)
            if key in occupied:
                continue
            occupied.add(key)
            parameters = re.sub(r"\s+", " ", match.group(2))
            signature = f"{match.group(1)}{parameters}"
            declarations.append(
                (kind, signature, f"Implements `{match.group(1)}` in this documentation surface.", line)
            )
    return sorted(declarations, key=lambda item: item[3])


def escape(value: str) -> str:
    return value.replace("|", "\\|").replace("[", "&#91;").replace("]", "&#93;")


def render() -> str:
    all_sources = sources()
    sections = []
    declaration_total = 0
    line_total = 0
    for path in all_sources:
        content = path.read_text(encoding="utf-8")
        line_total += len(content.splitlines())
        declarations = (
            python_declarations(path) if path.suffix == ".py" else javascript_declarations(path)
        )
        declaration_total += len(declarations)
        relative = path.relative_to(ROOT).as_posix()
        rows = [
            f"## `{relative}`",
            "",
            "| Kind | Signature | Responsibility | Source |",
            "|---|---|---|---|",
        ]
        for kind, signature, responsibility, line in declarations:
            rows.append(
                f"| {kind} | `{escape(signature)}` | {escape(responsibility)} | "
                f"[`{relative}:{line}`]({source_link(path, line)}) |"
            )
        if not declarations:
            rows.append(
                f"| module | `{relative}` | Configuration or import-only module. | "
                f"[`{relative}:1`]({source_link(path, 1)}) |"
            )
        rows.append("")
        sections.append("\n".join(rows))

    return (
        "<!-- Generated by scripts/generate-code-reference.py; do not edit. -->\n\n"
        "# Docs Code Reference\n\n"
        "Source map for every maintained function and configuration method in the "
        "Flyto2 Docs generators, audits, SEO gates, and VitePress configuration.\n\n"
        f"Inventory: **{len(all_sources)} files**, **{line_total} lines**, and "
        f"**{declaration_total} declarations**.\n\n"
        + "\n".join(sections)
    )


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    content = render()
    if args.check:
        if not OUTPUT.exists() or OUTPUT.read_text(encoding="utf-8") != content:
            print(f"generated reference drift: {OUTPUT.relative_to(ROOT)}", file=sys.stderr)
            return 1
        print(f"docs code reference checked: {OUTPUT.relative_to(ROOT)}")
        return 0
    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    OUTPUT.write_text(content, encoding="utf-8")
    print(f"docs code reference generated: {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
