#!/usr/bin/env python3
"""Sync source-backed Flyto2 Core documentation into the public docs site."""

from __future__ import annotations

import argparse
import posixpath
import re
import subprocess
import sys
from collections import defaultdict
from pathlib import Path


ROOT = Path(__file__).resolve().parents[1]
DEFAULT_CORE = ROOT.parent / "flyto-core"
CORE_DOCS = {
    "API.md": "core/api.md",
    "CLI.md": "core/cli.md",
    "CONFIGURATION.md": "core/configuration.md",
    "FEATURES.md": "core/features.md",
    "MIGRATION_STATUS.md": "core/migration-status.md",
    "OPERATIONS.md": "core/operations.md",
    "SECURITY_MODEL.md": "core/security-model.md",
    "TESTING.md": "core/testing.md",
    "WHITEPAPER.md": "core/whitepaper.md",
}
CORE_REFERENCE = {
    "README.md": "core/reference/index.md",
    "cli.md": "core/reference/cli.md",
    "configuration.md": "core/reference/configuration.md",
    "http-api.md": "core/reference/http-api.md",
    "recipes.md": "core/reference/recipes.md",
    "registered-modules.md": "core/reference/registered-modules.md",
    "source-modules.md": "core/reference/source-modules.md",
}
NARRATIVE_ROUTES = {
    source: f"/core/{Path(destination).stem}"
    for source, destination in CORE_DOCS.items()
}
REFERENCE_ROUTES = {
    source: (
        "/core/reference/"
        if source == "README.md"
        else f"/core/reference/{Path(destination).stem}"
    )
    for source, destination in CORE_REFERENCE.items()
}
LOCAL_LINK_RE = re.compile(r"\]\(([^)\s]+\.md)(#[^)]+)?\)")
PYTHON_SECTION_RE = re.compile(r"(?m)^## `([^`]+)`\n")


def core_commit(core_root: Path) -> str:
    result = subprocess.run(
        ["git", "-C", str(core_root), "rev-parse", "HEAD"],
        check=True,
        capture_output=True,
        text=True,
    )
    return result.stdout.strip()


def public_route(source_path: str, target: str) -> str:
    resolved = posixpath.normpath(
        posixpath.join(posixpath.dirname(source_path), target)
    )
    if resolved == "docs/TOOL_CATALOG.md":
        return "/modules/"
    if resolved == "docs/RECIPES.md":
        return "/core/reference/recipes"
    if resolved == "docs/YAML_WORKFLOW_SPEC.md":
        return "/guide/first-workflow"
    if resolved.startswith("docs/reference/"):
        name = posixpath.basename(resolved)
        if name == "python-api.md":
            return "/core/reference/python-api"
        return REFERENCE_ROUTES.get(name, f"/core/reference/{Path(name).stem}")
    if resolved.startswith("docs/"):
        name = posixpath.basename(resolved)
        if name in NARRATIVE_ROUTES:
            return NARRATIVE_ROUTES[name]
    return f"https://github.com/flytohub/flyto-core/blob/main/{resolved}"


def rewrite_links(content: str, source_path: str) -> str:
    def replace(match: re.Match[str]) -> str:
        route = public_route(source_path, match.group(1))
        return f"]({route}{match.group(2) or ''})"

    return LOCAL_LINK_RE.sub(replace, content)


def sync_header(commit: str) -> str:
    return (
        "<!-- Synced from flytohub/flyto-core@"
        f"{commit} by scripts/sync-core-reference.py; do not edit here. -->\n\n"
    )


def escape_vue_interpolation(content: str) -> str:
    content = content.replace("{{", "&#123;&#123;").replace("}}", "&#125;&#125;")
    return re.sub(
        r"<(/?[A-Za-z][A-Za-z0-9_-]*[^>\n]*)>",
        lambda match: f"&lt;{match.group(1)}&gt;",
        content,
    )


def transform(content: str, source_path: str, commit: str) -> str:
    generated = "<!-- Generated by scripts/generate_reference.py; do not edit. -->\n\n"
    if content.startswith(generated):
        content = content[len(generated) :]
    if source_path == "docs/reference/README.md":
        content = re.sub(
            r"^# Generated Reference$",
            "# Flyto2 Core Source Reference\n\n"
            "The Flyto2 Core source reference maps the maintained runtime, public "
            "interfaces, registrations, and generated inventories back to source.",
            content,
            count=1,
            flags=re.MULTILINE,
        )
    return sync_header(commit) + escape_vue_interpolation(
        rewrite_links(content, source_path)
    )


def python_group(source_path: str) -> str:
    module_prefix = "src/core/modules/"
    if source_path.startswith(module_prefix):
        parts = source_path[len(module_prefix) :].split("/")
        if len(parts) > 1 and parts[0] == "atomic":
            category = "root" if parts[1].endswith(".py") else parts[1]
            return f"modules-atomic-{category}"
        if len(parts) > 1:
            return f"modules-{parts[0]}"
        return "modules"
    rules = (
        ("src/cli/", "cli"),
        ("src/core/api/", "api"),
        ("src/core/browser/", "browser"),
        ("src/core/engine/", "engine"),
        ("src/core/runtime/", "runtime"),
        ("src/core/", "core"),
        ("scripts/", "maintenance"),
        ("examples/", "examples"),
        ("plugin-template/", "plugins"),
    )
    for prefix, group in rules:
        if source_path.startswith(prefix):
            return group
    return "other"


def display_segment(value: str) -> str:
    labels = {
        "ai": "AI",
        "api": "API",
        "dns": "DNS",
        "graphql": "GraphQL",
        "http": "HTTP",
        "k8s": "Kubernetes",
        "llm": "LLM",
        "mcp": "MCP",
        "ssh": "SSH",
        "third_party": "Third Party",
        "ui": "UI",
    }
    return labels.get(value, value.replace("_", " ").title())


def split_python_reference(content: str, commit: str) -> dict[str, str]:
    matches = list(PYTHON_SECTION_RE.finditer(content))
    groups: dict[str, list[tuple[str, str]]] = defaultdict(list)
    for index, match in enumerate(matches):
        end = matches[index + 1].start() if index + 1 < len(matches) else len(content)
        groups[python_group(match.group(1))].append((match.group(1), content[match.start() : end]))

    labels = {
        "api": "Execution And MCP API",
        "browser": "Browser Runtime",
        "cli": "CLI",
        "core": "Core Services",
        "engine": "Workflow Engine",
        "examples": "Examples",
        "maintenance": "Maintenance Scripts",
        "modules": "Module System",
        "other": "Other Sources",
        "plugins": "Plugin Template",
        "runtime": "Process Runtime",
    }
    outputs: dict[str, str] = {}
    index_rows = []
    for group in sorted(groups):
        sections = groups[group]
        body = escape_vue_interpolation(
            "".join(section for _, section in sections).rstrip() + "\n"
        )
        declaration_count = sum(
            1
            for line in body.splitlines()
            if line.startswith("| ") and not line.startswith("| Kind")
        )
        if group.startswith("modules-atomic-"):
            category = display_segment(group.removeprefix("modules-atomic-"))
            label = f"Modules: Atomic / {category}"
        elif group.startswith("modules-"):
            category = display_segment(group.removeprefix("modules-"))
            label = f"Modules: {category}"
        else:
            label = labels[group]
        destination = f"core/reference/python-api-{group}.md"
        outputs[destination] = (
            sync_header(commit)
            + f"# Python Declarations: {label}\n\n"
            + f"Source-backed signatures for **{declaration_count} declarations** "
            + f"across **{len(sections)} files** in the {label.lower()} area.\n\n"
            + body
        )
        index_rows.append(
            f"| [{label}](/core/reference/python-api-{group}) | "
            f"{len(sections)} | {declaration_count} |"
        )

    total_declarations = sum(
        int(row.rsplit("|", 2)[1].strip()) for row in index_rows
    )
    total_files = len(matches)
    outputs["core/reference/python-api.md"] = (
        sync_header(commit)
        + "# Flyto2 Core Python API Reference\n\n"
        + "The Flyto2 Core Python API reference indexes every maintained class, "
        + "function, nested function, and method below and splits them by "
        + "responsibility so the public "
        + "reference remains navigable.\n\n"
        + f"**{total_declarations} declarations across {total_files} files.**\n\n"
        + "| Area | Files | Declarations |\n"
        + "|---|---:|---:|\n"
        + "\n".join(index_rows)
        + "\n"
    )
    return outputs


def expected_outputs(core_root: Path) -> dict[str, str]:
    commit = core_commit(core_root)
    outputs: dict[str, str] = {}
    for source, destination in CORE_DOCS.items():
        source_path = core_root / "docs" / source
        outputs[destination] = transform(
            source_path.read_text(encoding="utf-8"), f"docs/{source}", commit
        )
    for source, destination in CORE_REFERENCE.items():
        source_path = core_root / "docs" / "reference" / source
        outputs[destination] = transform(
            source_path.read_text(encoding="utf-8"),
            f"docs/reference/{source}",
            commit,
        )
    python_source = (core_root / "docs" / "reference" / "python-api.md").read_text(
        encoding="utf-8"
    )
    outputs.update(split_python_reference(python_source, commit))
    return outputs


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--core-path", type=Path, default=DEFAULT_CORE)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    core_root = args.core_path.resolve()
    outputs = expected_outputs(core_root)
    stale = []
    for relative_path, content in outputs.items():
        destination = ROOT / relative_path
        if destination.exists() and destination.read_text(encoding="utf-8") == content:
            continue
        stale.append(relative_path)
        if not args.check:
            destination.parent.mkdir(parents=True, exist_ok=True)
            destination.write_text(content, encoding="utf-8")

    expected_python = {
        ROOT / path for path in outputs if path.startswith("core/reference/python-api-")
    }
    for existing in (ROOT / "core" / "reference").glob("python-api-*.md"):
        if existing not in expected_python:
            stale.append(str(existing.relative_to(ROOT)))
            if not args.check:
                existing.unlink()

    if args.check and stale:
        print("core reference drift detected:", file=sys.stderr)
        for path in stale:
            print(f"- {path}", file=sys.stderr)
        return 1
    action = "checked" if args.check else "synced"
    print(f"core reference {action}: {len(outputs)} pages from {core_root}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
